---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(ggthemes)
options(scipen = 999)

pi <- read.csv('coronavirusdataset/patientinfo.csv', na.strings=c("","NA"))
```

```{r}

## Cleaning
pi <- transform(pi, patient_id = as.numeric(patient_id),
                    infected_by = as.numeric(infected_by),
                    sex = as.factor(sex),
                    country = as.factor(country),
                    province = as.factor(province),
                    city = as.factor(city),
                    infection_case = as.factor(infection_case),
                    state = as.factor(state),
                    symptom_onset_date = as.Date(symptom_onset_date),
                    confirmed_date = as.Date(confirmed_date),
                    released_date = as.Date(released_date),
                    deceased_date = as.Date(deceased_date),
                    age = as.factor(age))
pi <- pi %>% select(-global_num, -birth_year, -country)

## Remove NAs of key variables for prediction
pi <- pi %>% drop_na(state, age, sex, confirmed_date)

## Unite released_date and deceased_date
pi <- pi %>% unite("outcome_date", released_date:deceased_date, remove = TRUE)
pi$outcome_date <- gsub("_NA", "", pi$outcome_date)
pi$outcome_date <- gsub("NA_", "", pi$outcome_date)
pi$outcome_date <- gsub("NA", NA, pi$outcome_date)
pi <- pi %>% transform(outcome_date = as.Date(outcome_date))

test = pi %>% filter(state == "deceased")

pi <- pi %>% mutate(days_passed = as.numeric(outcome_date - confirmed_date))

summary(pi)
sapply(pi,class)
colSums(is.na(pi))
```

```{r}
## Descriptive Statistics

# Cases per province bar chart
ggplot(pi, aes(x=province, fill = state)) + geom_bar(position="dodge") + ggtitle("Count of Cases per Province") +
  xlab("Province") + ylab("Count")  + theme_light() + theme(axis.text.x = element_text(angle = 90)) + coord_flip()

# Cases of age categories bar chart
ggplot(pi, aes(x=age, fill = state)) + geom_bar(position="stack") + ggtitle("Age Distribution of Cases") +
  xlab("Age") + ylab("Count") + theme_light() 
```

```{r}
## Train test split
index <- sample(1:nrow(pi), nrow(pi)*0.8, replace=F)
train <- pi[index,]
test <- pi[-index,]
```

```{r}
## Model building
library(ranger)
library(rpart)
library(rpart.plot)
library(pROC)

DT_model <- rpart(state ~ sex + age + province + confirmed_date, train, method = "class")
rpart.plot(DT_model, extra=104)

RF_model <- ranger(state ~ sex + age + province + confirmed_date, train, mtry=2, num.trees = 250, splitrule = "gini",importance = "impurity")

RF.pred <-predict(RF_model, test, type = "response")
RF.test.error <- mean(test$state!=RF.pred$predictions)
fitRF.roc <-roc(test$state, as.numeric(RF.pred$predictions)) 


```


